; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = A320_OverheadPanel
description = This is a project for the A320 LightPanel which can appear as an joystick under Windows.

[options]
platform = atmelavr
board = micro
framework = arduino
lib_deps = thijse/CmdMessenger@^4.1.0
unittesting_buildflag = -D unitTesting
                        -std=c++17
generic_hw_buildflag = -D generic_hw
                        -std=c++17
std_buildflag = -std=c++17
coverage_buildflag =
  -lgcov
  --coverage
  -fprofile-abs-path
  -Og
selected_tests =
  test_generic_circular*

[env]
lib_ldf_mode = deep

; [env:selected_generic_unittests]
; platform = native
; build_flags =
;   ${options.unittesting_buildflag}
;   ${options.generic_hw_buildflag}
;   ${options.coverage_buildflag}
; test_framework = unity
; test_filter = ${options.selected_tests}

; [env:all_generic_unittests]
; platform = native
; build_flags =
;   ${options.unittesting_buildflag}
;   ${options.generic_hw_buildflag}
;   ${options.coverage_buildflag}
; test_framework = unity
; test_filter = test_generic*
; check_src_filters =
;   lib/*
;   src/*
;   test/*

[env:micro]
platform = ${options.platform}
board = ${options.board}
framework = ${options.framework}
build_flags = ${options.std_buildflag}
board_build.mcu = atmega32u4
board_build.f_cpu = 16000000L
lib_deps = ${options.lib_deps}
board_build.usb_product = ${platformio.name}
extra_scripts = pre:.github/workflows/buildinfo.py

[env:target_application]
platform = ${options.platform}
board = ${options.board}
framework = ${options.framework}
build_flags = ${options.std_buildflag}
extra_scripts = pre:.github/workflows/buildinfo.py

[env:target_selected_unittests]
platform = ${options.platform}
board = ${options.board}
framework = ${options.framework}
build_flags = ${options.unittesting_buildflag}
test_framework = unity
test_filter = ${options.selected_tests}

[env:production_application]
platform = ${options.platform}
board = ${options.board}
framework = ${options.framework}
build_flags = ${options.std_buildflag}
