// ##########################################################################
// ### This file is generated by Build and Continuous Integration scripts ###
// ###   .github/workflows/buildinfo.py for local development environment ###
// ###   .github/workflows/testbuildrelease.yml for CI environment        ###
// ### Changes will be overwritten on the next build                      ###
// ##########################################################################

#include "buildinfo.h"

const buildEnvironment buildInfo::theBuildEnvironment{buildEnvironment::local};
const buildType buildInfo::theBuildType{buildType::development};
const int buildInfo::mainVersionDigit   = 0;
const int buildInfo::minorVersionDigit  = 0;
const int buildInfo::patchVersionDigit  = 1;
const char* buildInfo::lastCommitTag    = "8af36b2";
const char* buildInfo::buildTimeStamp   = "2024-Nov-07 19:40:51";
